title: Sudoku-solver
email: marc@sibert.fr
description: "Résolveur de Sudoku en Python avec interface TKinter (TK)"
baseurl: "" # Don't have any base path on my url. ie. /blog
url: "https://marcussacapuces91.github.io/Sudoku-solver/" 
# google_analytics: UA-000000000-0
# timezone: Australia/Brisbane
# show_excerpts: true # Show excerpts of posts on the home page
# permalink: /:categories/:title # Don't show the date of the post in the URL

# Social
twitter_username: LabAllen91
github_username: Marcussacapuces91
#linkedin_username: nathandench

# Build settings
# markdown: kramdown
theme: jekyll-theme-leap-day
#plugins:
#  - jekyll-feed
#  - jekyll-sitemap # I added this to automatiacally generate a sitemap.xml
